import type { Metadata } from "next";

import { Anton,Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const anton = Anton({ subsets: ['latin'], weight: ['400'],variable: '--font-anton' })
const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'],variable: '--font-plus_jakarta_sans' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      {/* 3. Letak className kat body */}
     <body className={`${jakarta.className} ${anton.variable}`}>
        {children}
      </body>
    </html>
  );
}
